Feat/ali blocks
muratkali/18-web-plus-varvary-friends-fons pull request #13
Opened 2022-11-21 22:40 UTC by muratkali

Саша, привет! Сорри за задержку, закинул свои три блока на проверку:

1. Страница “Программы. Московская школа профессиональной филантропии”: Блок “Для чего мы это делаем?” (28)
2. Страница “Программы. Команда профессионалов”: Баннер (38)
3. Страница «Для бизнеса»: Блок “Что мы делаем?” (47)

У меня много мелких недочетов и проблемы с адаптивом, плюс очень кондово сделан javascript и слайдер. Надеюсь, тебя это не испугает. Пиши в личку, если появятся вопросы.

2022-11-22 08:24 UTC, alex-markin requested changes
Али, привет. 

Всё отлично, есть несколько шероховатостей по части верстки и адаптива. По JS проблем не увидел - слайдер работает так, как должен - и хорошо.

2022-11-22 08:24 UTC, alex-markin commented on pages/index.css
> +/*  */
Это не к твоей работе коммент, но всё же: надо будет потом унифицировать комментарии, обозначающие секции, а то сейчас там пропуски

2022-11-22 08:24 UTC, alex-markin commented on scripts/gallery.js
> +startSlide();
Может это и можно как-то красивенько написать, но по мне так всё работает и отлично))

2022-11-22 08:24 UTC, alex-markin commented on philanthropy-school-page.html
> +      </ul>
<img width="622" alt="Screenshot 2022-11-22 at 11 14 38" src="https://user-images.githubusercontent.com/111679267/203260761-79128c3a-0967-47c5-bfee-74ea76ed5326.png">

Между списком и кнопкой сейчас двойной пропуск из margin и gap. Надо оставить что-то одно.

2022-11-22 08:24 UTC, alex-markin commented on philanthropy-school-page.html
> +    <section class="activity">
Расстояние от кнопки до следующего элемента снизу сейчас 152 px, сверху 72px. А в работе сейчас 96 с двух сторон

2022-11-22 08:24 UTC, alex-markin commented on philanthropy-school-page.html
> +      <h2 class="section__title section__title_activity">Для чего мы это делаем</h2>
"Для чего мы это делаем?" - нет знака вопроса

2022-11-22 08:24 UTC, alex-markin commented on philanthropy-school-page.html
> +      <h2 class="section__title section__title_activity">Для чего мы это делаем</h2>
И тут же в адаптиве заголовок не центрирован. Скорее всего это тянется еще с моего модификатора. section__title_activity. Можно добавить text-align: center;
<img width="258" alt="Screenshot 2022-11-22 at 11 21 29" src="https://user-images.githubusercontent.com/111679267/203262357-12e5411e-399d-4304-8091-3f3a3a4cc788.png">

2022-11-22 15:56 UTC, muratkali commented on for-business-page.html
> +        <li class="listing__point listing__point_mobile-hide">Разработка образовательных и&nbsp;волонтерских проектов в&nbsp;области благотворительности.</li>
спасибо за замечание, убрал listing__point_mobile-hide

2022-11-22 16:00 UTC, muratkali commented on blocks/gallery/__button/gallery__button.css
> +}
да, возникла путаница с баттонами, убрал пустой класс, переписал путь в index.css, добавил .gallery__button кнопкам

2022-11-22 16:01 UTC, muratkali commented on blocks/gallery/__button/_type/gallery__button_type_previous.css
> +    margin-left: 20px;
да, абсолютное позиционирование было прописано в классе .gallery__button, который я забыл присвоить кнопкам ^^

2022-11-22 16:02 UTC, muratkali commented on blocks/gallery/__button/gallery_button.css
> +}
даааа, это я в ночи уже парился) исправил

2022-11-22 16:14 UTC, muratkali commented on blocks/gallery/__item/gallery__item.css
> +    height: 100vh;
спасибо, исправил

2022-11-22 16:14 UTC, muratkali commented on blocks/gallery/__item/gallery__item.css
> +
да, понимаю, сейчас просто делаю максимальным кондовым способом :/

2022-11-22 16:22 UTC, muratkali commented on blocks/gallery/__item/gallery__item.css
> +    min-height: 200px;
спасибо, исправил, привязал высоту к ширине экрана через calc()

2022-11-22 16:33 UTC, muratkali commented on philanthropy-school-page.html
> +    <section class="activity">
да, прописал отдельный модификатор activity_page_philantropy, поправил

2022-11-22 16:34 UTC, muratkali commented
@alex-markin Саша, спасибо за ревью, поправил большую часть моментов :)

2022-11-23 06:28 UTC, alex-markin commented on blocks/gallery/__item/gallery__item.css
> +    min-height: 200px;
Я уже придираюсь, но  на 1280 ширине высота 640 у картинки. Думаю, что это потом хот фиксом можно пофиксить через max-width: 600px

2022-11-23 06:34 UTC, alex-markin reviewed
Али, привет. Всё проверил. Кроме пары нюансов со слайдером, которые можно потом отдельно поправить, можно мерджить.

2022-11-23 06:34 UTC, alex-markin commented on blocks/gallery/__button/gallery__button.css
> +    top: 50%;
Опять же - придираюсь. Потом поправим фиксом - стрелки слайдера сейчас не посередине, а ближе к верху картинок.

2022-11-23 06:36 UTC, alex-markin approved these changes

2022-11-23 06:37 UTC, alex-markin commented
Али, привет. Всё проверил. Кроме пары нюансов со слайдером, которые можно потом отдельно поправить, можно мерджить.

2022-11-23 06:43 UTC, merged